hmcts/probate-commons

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/documents/BulkScanCoverSheet.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/BusinessDocument.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/CheckAnswersSummary.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/DeclarationItem.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/DeclarationSection.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/LegalDeclaration.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/QuestionAndAnswerRow.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/Section.java

https://tools.hmcts.net/jira/browse/PRI-140

Pri 140 add business document

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/standingsearch/StandingSearchData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/willlodgement/WillLodgementData.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/resources/intestacyGrantOfRepresentation.json

Check any usage of commons can successfully handle these legacy url changes

PRO-4732: added links to legacy case types from ccd views

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/ProbateType.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/Form.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/InheritanceTax.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/Will.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/Executor.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/Executors.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaApplicant.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaCopies.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaDeclaration.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaDeclarationDeclaration.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaLegalStatement.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaLegalStatementExecutorApplying.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/Summary.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/paForm.json

Created initial form class for PA, this will be used as the contract to orchestrator and will be mapped to grant of representation.
```
[ ] Yes
[ X] No
```

PRO-4817: Added initial PA form classes

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/resources/intestacyGrantOfRepresentation.json

https://tools.hmcts.net/jira/browse/PRO-4840
Adding solsSolicitorFirmName to GrantOfRepresentationData.java
```
[ ] Yes
[X] No
```

PRO-4840 update legacy data mapper solicitors

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/SolsAliasName.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/standingsearch/StandingSearchData.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/StandingSearchDataCreator.java
src/test/resources/caveatData.json
src/test/resources/intestacyGrantOfRepresentation.json
src/test/resources/standingSearchData.json

https://tools.hmcts.net/jira/browse/PRO-4941
Added solsAliasName to the data structure to support the alias structure in the BO flow. Updated data type for deceasedAnyOtherNames to a boolean yes/no field. Updated tests
```
[ ] Yes
[X] No
```

PRO-4941 Legacy Import Structure

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatForm.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/validation/CaveatDataValidationTest.java
src/test/resources/caveatData.json

change caveat submission identifier
[ ] Yes
[x ] No
```

Pro 5001 change caveat submission identifier

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/RegistryLocation.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/RegistryLocationTest.java

Add ctsc to registry locations
[ ] Yes
[ x] No
```

Pro 5089 Add ctsc to registry locations

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java

Added new field which is saved to CCD, and is required when raising caveat and creating notifcation with back-office.
```
[ ] Yes
[X] No
```

PRO-5198: Added notification request field

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseState.java

PRO-5198: Added caveat raised state.

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/standingsearch/StandingSearchData.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/StandingSearchDataCreator.java
src/test/resources/caveatData.json
src/test/resources/standingSearchData.json

https://tools.hmcts.net/jira/browse/PRO-5095
updated caveat and ss data to include application date
```
[ ] Yes
[x] No
```

updated caveat and ss data to include application date

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocument.java
src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocumentLink.java
src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocumentType.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java

Added notification documents to caveat data
```
[ ] Yes
[X] No
```

PRO-5198: Added notification documents to caveat data

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/standingsearch/StandingSearchData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/willlodgement/WillLodgementData.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/StandingSearchDataCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/WillLodgementDataCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/CaseTypeTest.java
src/test/resources/caveatData.json
src/test/resources/intestacyGrantOfRepresentation.json
src/test/resources/standingSearchData.json
src/test/resources/willLodgementData.json

https://tools.hmcts.net/jira/browse/PRO-5356
Defaulting Caveat and PA applications to digital in CCD
```
[ ] Yes
[x] No
```

Pro 5356 default applications to digital grant

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/ProbateType.java
src/test/resources/intestacyForm.json
src/test/resources/paForm.json

Update probateType values to match FE.
```
[ ] Yes
[X] No
```

PRO-5247: Update probateType values to match FE.

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/BulkScanCoverSheet.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/CheckAnswersSummary.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/LegalDeclaration.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/DocumentUpload.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/Documents.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaForm.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/intestacyForm.json
src/test/resources/intestacyGrantOfRepresentation.json

- Added SOT document to DTOs for both form and case
- Added uploaded documents for both form and case
- Fixed PDF generation to business service
```
[ ] Yes
[X] No
```

PRO-5247: Added SOT doc and uploaded documents, also fixed pdf generation

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

Added registry address, sequence number and registry email - this allow them to be persisted to CCD. Required for coversheet pdf.
```
[ ] Yes
[X] No
```

PRO-5247: Added registry address, sequence number and registry email.

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/ScannedDocument.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatDataTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationDataIntestacyTest.java
src/test/resources/bulkScanCaveatData.json
src/test/resources/bulkScanIntestacyGrantOfRepresentation.json

https://tools.hmcts.net/jira/browse/PRO-5804
Update to add Scanned Documents list to Grant of Representation and Ceveats case types. This change is required as these cases definitions will be used for bulk scanning phase 2 to create a new case. 
```
[ ] Yes
[x] No
```

PRO-5804: Update to add scanned documents to caveats and gor.

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/ExecutorApplying.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/ProbateApplicant.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/ProbateDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/Executor.java
src/test/resources/intestacyForm.json

PRO-6212: Update version to 0.0.63

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/resources/bulkScanIntestacyGrantOfRepresentation.json
src/test/resources/intestacyGrantOfRepresentation.json

https://tools.hmcts.net/jira/browse/PRO-5804
Correcttion to attorneyOnBehalfOfNameAndAddress name to match ccd.
```
[ ] Yes
[x] No
```

PRO-5804: BSP correct bulk scan ccd field mapping

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/InOut.java
src/test/resources/bulkScanIntestacyGrantOfRepresentation.json

https://tools.hmcts.net/jira/browse/PRO-5804
Correction to in out values being returned with wrong caps.
```
[ ] Yes
[x] No
```

PRO-5804: Updated to return inout values correctly.

---

src/main/java/uk/gov/hmcts/reform/probate/model/InOut.java
src/test/resources/bulkScanIntestacyGrantOfRepresentation.json

https://tools.hmcts.net/jira/browse/PRO-5804
Update to create commons 1.0.1 to put back inout fix for bulk scanning phase 2.
```
[ ] Yes
[x] No
```

PRO-5804-Update to correct inout for bulk scanning

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseState.java

PRO-6786: Added all post create case states to CaseState

---

src/main/java/uk/gov/hmcts/reform/probate/model/IhtFormType.java

1.0.2 iht defaults fix

---

src/main/java/uk/gov/hmcts/reform/probate/model/IhtFormType.java

PRO-6387: change json value of NA on IhtFormType

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java

https://tools.hmcts.net/jira/browse/PRO-6885
Fix prod caveats validation issue for dob unknown
```
[ ] Yes
[x] No
```

PRO-6885: Change the validation for dob and dob

---

src/main/java/uk/gov/hmcts/reform/probate/model/InOut.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/BulkPrint.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseMatch.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseState.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/EventId.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/test/resources/bulkScanIntestacyGrantOfRepresentation.json

Add caveat attributes for expiry usage

PRO-5170: added caveat fields needed for expiry function

---

src/main/java/uk/gov/hmcts/reform/probate/model/PaymentStatus.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationPaSubmissionTest.java

https://tools.hmcts.net/jira/browse/PRO-6841
Remove payment pending status code
```
[ ] Yes
[x] No
```

PRO-6841: Remove payment pending status code

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

Pro 6913 add awaiting doc attrs

---

src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocumentType.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/resources/bulkScanIntestacyGrantOfRepresentation.json
src/test/resources/intestacyGrantOfRepresentation.json

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/WLA-458
Change description
[BO] Grant delayed Notification - DocMosis Bulk Print
Added bulkprint letter ID
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X] No

WLA-458: REVERT

---

.github/workflows/gradle.yml
README.md
build.gradle

PRO-7900: updating to java 11

---

.github/workflows/gradle.yml
README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
settings.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/Equality.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaForm.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/bulkScanCitizenCaveatData.json
src/test/resources/bulkScanIntestacyCitizenGrantOfRepresentation.json
src/test/resources/bulkScanIntestacySolicitorGrantOfRepresentation.json
src/test/resources/bulkScanSolicitorCaveatData.json
src/test/resources/caveatData.json
src/test/resources/caveatForm.json
src/test/resources/intestacyForm.json
src/test/resources/intestacyGrantOfRepresentation.json
src/test/resources/paForm.json

https://tools.hmcts.net/jira/browse/PRO-7900
Gradle version upgrade 
```
[ ] Yes
[X ] No
```

PRO-7900 upgrade gradle version

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/Equality.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaForm.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/bulkScanCitizenCaveatData.json
src/test/resources/bulkScanIntestacyCitizenGrantOfRepresentation.json
src/test/resources/bulkScanIntestacySolicitorGrantOfRepresentation.json
src/test/resources/bulkScanSolicitorCaveatData.json
src/test/resources/caveatData.json
src/test/resources/caveatForm.json
src/test/resources/intestacyForm.json
src/test/resources/intestacyGrantOfRepresentation.json
src/test/resources/paForm.json

https://tools.hmcts.net/jira/browse/PRO-7229
Update to add pcqId to commons forms and data models used in pa journeys.
```
[ ] Yes
[x] No
```

PRO-7229 Update to support pcqId

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/DeathCertificate.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/ProbateDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaDeceased.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/bulkScanIntestacyCitizenGrantOfRepresentation.json
src/test/resources/bulkScanIntestacySolicitorGrantOfRepresentation.json
src/test/resources/intestacyGrantOfRepresentation.json
src/test/resources/paForm.json

https://tools.hmcts.net/jira/browse/DTSPB-529
https://tools.hmcts.net/jira/browse/DTSPB-534
https://tools.hmcts.net/jira/browse/DTSPB-535
New death cert flow processes
```
[ ] Yes
[x] No
```

Dtspb 529 new death cert process

---

src/main/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatDeceased.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatFormTest.java
src/test/resources/caveatForm.json

PRO-5837: Deceased Alias Field Added

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/DeathRecord.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

https://tools.hmcts.net/jira/browse/DTSPB-1526
Add list of DeathRecords for Life Event Verification
```
[ ] Yes
[x] No
```

DTSPB-1526: add list of DeathRecords for Life Event Verification

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/DocumentType.java

DTSPB-1775: added will to doc type

---

.github/workflows/gradle.yml
.github/workflows/jitpack_build.yml
README.md
jitpack.yml
src/test/java/uk/gov/hmcts/reform/probate/model/payments/PaymentDtoTest.java

Dtspb 1818 migrate to jitpack
Dtspb 1818 migrate to jitpack
```
[ ] Yes
[x] No
```

Dtspb 1818 migrate to jitpack

---

README.md
src/main/java/uk/gov/hmcts/reform/probate/model/cases/DocumentType.java

DTSPB-1599: added LS uploaded doc type

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/DeathRecord.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

https://tools.hmcts.net/jira/browse/DTSPB-1526
Add death records for Life Event Verification
```
[ ] Yes
[X] No
```

Re-add "DTSPB-1526: add list DeathRecords for Life Event Verification"

---

src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocumentType.java

https://tools.hmcts.net/jira/browse/DTSPB-1176
add sol coversheet document link to commons
```
[ ] Yes
[x] No
```

DTSPB-1176 add sol coversheet

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/ExecutorApplying.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/ExecutorNotApplying.java

Fix prod issue with TC 
```
[ ] Yes
[ X ] No
```

Add the missing TC Field

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/LegalStatement.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/LegalStatementHolder.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/paForm.json

https://tools.hmcts.net/jira/browse/DTSPB-2482
Legal statement change for excepted estate
```
[ ] Yes
[X] No
```

DTSPB-2482: EE legal statement change

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationPaValidationTest.java

https://tools.hmcts.net/jira/browse/DTSPB-2493
Make ihtFormCompletedOnline optional
```
[ ] Yes
[x] No
```

DTSPB-2493: Make ihtFormCompletedOnline optional

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationTest.java

DTSPB-2544-PP-notorial-access 1.3.8

---

config/checkstyle/checkstyle.xml
src/main/java/uk/gov/hmcts/reform/probate/model/cases/Organisation.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/OrganisationPolicy.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatDataTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationDataIntestacyTest.java
src/test/resources/caveatDataWithOrg.json
src/test/resources/intestacyGrantOfRepresentationWithOrg.json

Include org data in common model - ready for SAC changes

DTSPB-2781-incl-organisation-1.3.9-DTSPB-2781

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationPaValidationTest.java

https://tools.hmcts.net/jira/browse/DTSPB-2705
change commons rule to allow dob to equal dod
```
[ ] Yes
[x] No
```

DTSPB-2705 allow dob to equal dod

---

build.gradle
src/main/java/uk/gov/hmcts/reform/probate/model/idam/TokenRequest.java
src/main/java/uk/gov/hmcts/reform/probate/model/idam/TokenResponse.java
src/main/java/uk/gov/hmcts/reform/probate/model/idam/UserInfo.java

DTSPB-2672: implementing Open ID Connect (OICD)

---

src/main/java/uk/gov/hmcts/reform/probate/model/documents/BulkScanCoverSheet.java

https://tools.hmcts.net/jira/browse/DTSPB-2725
add new message if no documents are required on PA coversheet
```
[ ] Yes
[x] No
```

Dtspb 2725 no docs required

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyApplicant.java

https://tools.hmcts.net/jira/browse/DTSPB-2858
new no docs required field used for checking which applicant received email we will use
```
[ ] Yes
[x] No
```

DTSPB-2858 new no docs required field

---

build.gradle
src/test/java/uk/gov/hmcts/reform/probate/model/cases/CaseTypeTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/RegistryLocationTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatDataTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationDataIntestacyTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationPaSubmissionTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationPaValidationTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/standingsearch/StandingSearchDataTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/willlodgement/WillLodgementDataTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/jackson/BigDecimalDeserializerTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/payments/CardPaymentRequestTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/payments/PaymentDtoTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/validation/AtLeastOneNonEmptyFieldValidatorTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/validation/CaveatDataValidationTest.java

DTSPB-1714: initial commit

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/DocumentType.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/ProbateFee.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/ProbateFeeNotIncludedReason.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/resources/bulkScanSolicitorCaveatData.json

https://tools.hmcts.net/jira/browse/DTSPB-2407
https://tools.hmcts.net/jira/browse/DTSPB-2656
Bulk scan caveat form changes
```
[ ] Yes
[ ] No
```

Dtspb 2407 pa8 a and dtspb 2656 pa8 b

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/DocumentType.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/ProbateFee.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/ProbateFeeNotIncludedReason.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/resources/bulkScanSolicitorCaveatData.json

https://tools.hmcts.net/jira/browse/DTSPB-2407
https://tools.hmcts.net/jira/browse/DTSPB-2656
Bulk scan caveat form changes
```
[ ] Yes
[ ] No
```

DTSPB-2407 PA8A and DTSPB-2656 PA8B

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseState.java

https://tools.hmcts.net/jira/browse/DTSPB-3239
```
[ ] Yes
[X] No
```

Add dormant state

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/RegistrarDirection.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatData.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/CaveatCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/RegistrarDirectionCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/caveat/CaveatDataTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationTest.java

https://tools.hmcts.net/jira/browse/DTSPB-3361
```
[ ] Yes
[ ] No
```

Dtspb 3361 add registrars decision

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/test/java/uk/gov/hmcts/reform/probate/model/GrantOfRepresentationCreator.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationDataIntestacyTest.java
src/test/resources/intestacyGrantOfRepresentationStoppedWithEvidence.json

https://tools.hmcts.net/jira/browse/DTSPB-3242
added json property to GOR data, and added tests for serialisation to and from yesNo
```
[ ] Yes
[x] No
```

DTSPB-3242

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseState.java

https://tools.hmcts.net/jira/browse/DTSPB-3405
```
[ ] Yes
[x] No
```

DTSPB-3405 Case Worker Escalation State 1.4.10

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaForm.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/intestacyForm.json
src/test/resources/paForm.json

https://tools.hmcts.net/jira/browse/DTSPB-3577
Citizen hub Docs received status fix
Add documentsReceivedNotificationSent field
```
[ ] Yes
[x] No
```

DTSPB-3577 Add documentsReceivedNotificationSent field

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseState.java

https://tools.hmcts.net/jira/browse/DTSPB-3449
Added new state Post grant Issued state
```
[ ] Yes
[X] No
```

Dtspb 3449 post grant issue

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

DTSPB-3640
```
[ ] Yes
[x] No
```

DTSPB-3640-1.4.16

---

src/main/java/uk/gov/hmcts/reform/probate/model/forms/InheritanceTax.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/intestacyForm.json
src/test/resources/paForm.json

DTSPB-3705 new value for calc completed page

---

jitpack.yml
src/main/java/uk/gov/hmcts/reform/probate/model/IhtFormEstate.java
src/main/java/uk/gov/hmcts/reform/probate/model/IhtFormType.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/InheritanceTax.java

DTSPB-3705 further changes

---

.github/workflows/gradle.yml
build.gradle

Spring downgrade

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/ProbateDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaDeceased.java

Dtspb 4070 deceased will name rems

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/ProbateDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaDeceased.java

Reverts hmcts/probate-commons#189

Revert "Dtspb 4070 deceased will name rems"

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/ProbateDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyDeceased.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaDeceased.java

Dtspb 4070 update commons

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

https://tools.hmcts.net/jira/browse/DTSPB-4270

DTSPB-4270 Long term fix for Data Migration cases

---

src/main/java/uk/gov/hmcts/reform/probate/model/multiapplicant/ExecutorNotification.java

https://tools.hmcts.net/jira/browse/DTSPB-4087

change localdate to string

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/DocumentLink.java

https://tools.hmcts.net/jira/browse/DTSPB-4115

DTSPB-4115 add upload time stamp to document link 

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantType.java

DTSPB-4293
Added new case type
Testing on Demo

DTSPB-4293 Ad Colligenda Bona changes

---

src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocumentLink.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/DocumentLink.java

See [DTSPB-4115](https://tools.hmcts.net/jira/browse/DTSPB-4115:)

DTSPB-4115: Add serialisation

---

src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyForm.java

DTSPB-4222
fix missing assetsoverseas in IntestacyForm

DTSPB-4222 fix missing assetsoverseas in IntestacyForm

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyForm.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaForm.java
src/test/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationPaSubmissionTest.java

DTSPB-4582
Submitted date fix
Testing on Preview

DTSPB-4582 Submitted date fix

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/CaseInfo.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/EventId.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/CcdCase.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/Form.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/caveat/CaveatFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/intestacy/IntestacyFormTest.java
src/test/java/uk/gov/hmcts/reform/probate/model/forms/pa/PaFormTest.java
src/test/resources/caveatForm.json
src/test/resources/intestacyForm.json
src/test/resources/paForm.json

DTSPB-4475
Update models for Retain and Disposal change

DTSPB-4475 Update models for Retain and Disposal change

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java
src/main/java/uk/gov/hmcts/reform/probate/model/forms/pa/Executors.java

DTSPB-4361
Executor not accounted for changes

DTSPB-4361 Added new field for Executor not accounted change

---

src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

DTSPB-4514
DTSPB-4580
add firstStopReminderSentDate

DTSPB-4514 DTSPB-4580 add firstStopReminderSentDate

---

probate-pact-commons/README.md
probate-pact-commons/build.gradle
probate-pact-commons/src/main/java/uk/gov/hmcts/reform/probate/pact/dsl/ObjectMapperTestUtil.java
probate-pact-commons/src/main/java/uk/gov/hmcts/reform/probate/pact/dsl/PactDslBuilderForCaseDetailsList.java
probate-pact-commons/src/main/java/uk/gov/hmcts/reform/probate/pact/dsl/ResourceLoader.java
settings.gradle

See [DTSPB-4761](https://tools.hmcts.net/jira/browse/DTSPB-4761)
Moves the (archived) github.com/hmcts/probate-pact-commons here as a child project. this should publish into azure artifacts.
built locally - unclear whether this will just work in azure.

DTSPB-4761 Move pact commons

---

src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocumentType.java

DTSPB-4514
Add missing probateDocumentTypeEnum

DTSPB-4514 Add missing probateDocumentTypeEnum

---

src/main/java/uk/gov/hmcts/reform/probate/model/ProbateDocumentType.java
src/main/java/uk/gov/hmcts/reform/probate/model/cases/grantofrepresentation/GrantOfRepresentationData.java

DTSPB-4661 Paper notification for dormant cases
- [ X] Does this PR introduce a breaking change

DTSPB-4661 Paper notification for dormant cases

---

src/main/java/uk/gov/hmcts/reform/probate/model/documents/CheckListItemType.java
src/main/java/uk/gov/hmcts/reform/probate/model/documents/Segment.java

DTSPB-4740
Added new fields for Bulkscan coversheet
Need to test on Preview

DTSPB-4740 Added new checkList type

---

src/main/java/uk/gov/hmcts/reform/probate/model/Relationship.java

See [DTSPB-4697](https://tools.hmcts.net/jira/browse/DTSPB-4697)
Adds new fixedlist value to mapping.

DTSPB-4697 Add grandchild to relationship map.
